#!/usr/bin/env python3
import os, sys, glob


def format_file_name(fn: str) -> str:
    frags = fn.split("/")
    if len(frags) >= 3:
        return "/".join(frags[-3:])
    return fn


def get_func_cov(cov_file: str) -> dict[str, dict[str, bool]]:
    # file -> func -> covered
    cov_data = {}

    cur_file = None
    cur_func = None

    covf = open(cov_file, "r")
    for line in covf:
        line = line.strip()
        if line == "":
            continue
        line = line.split(" ")

        if len(line) < 2:
            continue

        if line[0] == "File":
            cur_file = format_file_name(line[1])
            cov_data[cur_file] = {}
            continue

        if line[0] == "F":
            cur_func = line[1]
            cov_data[cur_file][cur_func] = False
            continue

        covered = line[2] == "1"
        cov_data[cur_file][cur_func] = cov_data[cur_file][cur_func] or covered

    covf.close()
    return cov_data


def main(argv):
    if len(argv) < 2:
        print(f"Usage: {argv[0]} (<cov_output_dir> or <cov_output_fn>)")
        print("  It computes BB coverage statistics from coverage output files.")
        print(
            "  <cov_output_dir>: Directory containing coverage output files generated by get_cov.py"
        )
        print("  <cov_output_fn>: A single coverage output file")

        return 1

    cov_target = argv[1]
    if not os.path.exists(cov_target):
        print(f"Cov target {cov_target} does not exist")
        return 1

    output_fn = None
    if len(argv) >= 3:
        output_fn = argv[2]
        if os.path.exists(output_fn):
            print(f"Output file {output_fn} already exists")
            return 1

    cov_files = []
    if os.path.isfile(cov_target):
        cov_files = [cov_target]
    else:
        cov_dir = cov_target
        cov_files = glob.glob(f"{cov_dir}/*")
        if len(cov_files) == 0:
            print(f"No coverage files found in {cov_dir}")
            return 1

    cov_files.sort()

    acc_func_cov = set()

    for cov_file in cov_files:
        if not os.path.isfile(cov_file):
            continue

        cov_data = get_func_cov(cov_file)

        basename = os.path.basename(cov_file)
        if len(cov_data) == 0:
            print(f"[{basename}] No function coverage data found")
            continue

        new_func_cov = set()
        for file in cov_data:
            for func in cov_data[file]:
                covered = cov_data[file][func]
                if not covered:
                    continue
                if (file, func) in acc_func_cov:
                    continue
                new_func_cov.add((file, func))
                acc_func_cov.add((file, func))

        print(f"[{basename}] Covered new functions: {len(new_func_cov)}")
        for idx, (file, func) in enumerate(new_func_cov):
            print(f" [{idx}] {file}::{func}")


if __name__ == "__main__":
    sys.exit(main(sys.argv))
