#!/usr/bin/env python3
import os, sys, glob, tqdm
import json


def get_bb_cov(cov_file: str) -> dict[str, dict[str, dict[str, bool]]]:
    # file -> func -> bb -> covered
    cov_data = {}

    cur_file = None
    cur_func = None
    cur_bb = None

    covf = open(cov_file, "r")
    for line in covf:
        line = line.strip()
        if line == "":
            continue
        line = line.split(" ")

        if len(line) < 2:
            continue

        if line[0] == "File":
            cur_file = " ".join(line[1:])
            cov_data[cur_file] = {}
            continue

        if line[0] == "F":
            cur_func = " ".join(line[1:-1])
            cov_data[cur_file][cur_func] = {}
            continue

        cur_bb = line[1]
        covered = line[2] == "1"
        cov_data[cur_file][cur_func][cur_bb] = covered

    covf.close()
    return cov_data


def main(argv):
    if len(argv) < 2:
        print(f"Usage: {argv[0]} (<cov_output_dir> or <cov_output_fn>) [<output.json>]")
        print("  It computes BB coverage statistics from coverage output files.")
        print(
            "  <cov_output_dir>: Directory containing coverage output files generated by get_cov.py"
        )
        print("  <cov_output_fn>: A single coverage output file")
        print(
            "  <output.json>: (Optional) Output file name to save coverage statistics as JSON"
        )
        return 1

    cov_target = argv[1]
    if not os.path.exists(cov_target):
        print(f"Cov target {cov_target} does not exist")
        return 1

    output_fn = None
    if len(argv) >= 3:
        output_fn = argv[2]
        if os.path.exists(output_fn):
            print(f"Output file {output_fn} already exists")
            return 1

    cov_files = []
    if os.path.isfile(cov_target):
        cov_files = [cov_target]
    else:
        cov_dir = cov_target
        cov_files = glob.glob(f"{cov_dir}/*")
        if len(cov_files) == 0:
            print(f"No coverage files found in {cov_dir}")
            return 1

    num_zero_cov = 0

    # accumulated coverage data
    # file -> func -> bb -> num_covered_inputs
    acc_bb_cov = dict()
    acc_func_cov = dict()

    func_cov_sum = 0

    bb_cov_sum = 0

    num_inputs = 0

    for cov_file in tqdm.tqdm(cov_files):
        if not os.path.isfile(cov_file):
            continue

        num_inputs += 1

        cov_data = get_bb_cov(cov_file)
        if len(cov_data) == 0:
            num_zero_cov += 1
            continue

        bb_cov = 0

        for file in cov_data:
            if file not in acc_bb_cov:
                acc_bb_cov[file] = dict()
                acc_func_cov[file] = dict()

            for func in cov_data[file]:
                if func not in acc_bb_cov[file]:
                    acc_bb_cov[file][func] = dict()
                    acc_func_cov[file][func] = 0

                is_func_covered = False

                for bb in cov_data[file][func]:
                    if bb not in acc_bb_cov[file][func]:
                        acc_bb_cov[file][func][bb] = 0

                    if cov_data[file][func][bb]:
                        acc_bb_cov[file][func][bb] += 1
                        bb_cov += 1
                        is_func_covered = True

                if is_func_covered:
                    func_cov_sum += 1
                    acc_func_cov[file][func] += 1

        bb_cov_sum += bb_cov

        if bb_cov == 0:
            num_zero_cov += 1

    avg_bb_cov = bb_cov_sum / num_inputs if num_inputs > 0 else 0
    avg_func_cov = func_cov_sum / num_inputs if num_inputs > 0 else 0

    threshold_99 = int(0.99 * num_inputs)
    num_bbs_always_covered = 0
    num_bbs_99_covered = 0

    accumulated_func_cov = 0
    accumulated_bb_cov = 0
    for file in acc_bb_cov:
        for func in acc_bb_cov[file]:
            for bb in acc_bb_cov[file][func]:
                if acc_bb_cov[file][func][bb] > 0:
                    accumulated_bb_cov += 1

                    if acc_bb_cov[file][func][bb] == num_inputs:
                        num_bbs_always_covered += 1
                    if acc_bb_cov[file][func][bb] >= threshold_99:
                        num_bbs_99_covered += 1

    funcs_always_covered = set()
    funcs_99_covered = set()

    for file in acc_bb_cov:
        for func in acc_bb_cov[file]:
            if acc_func_cov[file][func] > 0:
                accumulated_func_cov += 1
            if acc_func_cov[file][func] == num_inputs:
                funcs_always_covered.add((file, func))
            if acc_func_cov[file][func] >= threshold_99:
                funcs_99_covered.add((file, func))

    print(f"# of funcs always covered: {len(funcs_always_covered)}")
    for idx, (file, func) in enumerate(funcs_always_covered):
        print(f"  [{idx}]{file}::{func}")

    print(f"# of funcs 99% covered: {len(funcs_99_covered)}")
    for idx, (file, func) in enumerate(funcs_99_covered):
        print(f"  [{idx}]{file}::{func}")

    print("\n==== Coverage Statistics ====")
    print(f"Total # of cov files: {num_inputs}")
    print(f"Avg. # of covered funcs: {avg_func_cov:.2f}")
    print(f"Avg. # of covered BBs: {avg_bb_cov:.2f}")
    print(f"# of cov files with zero covered BBs: {num_zero_cov}")

    print(f"Total # of source files : {len(acc_bb_cov)}")
    total_funcs = 0
    for file in acc_bb_cov:
        total_funcs += len(acc_bb_cov[file])
    print(f"Total # of functions : {total_funcs}")
    total_bbs = 0
    for file in acc_bb_cov:
        for func in acc_bb_cov[file]:
            total_bbs += len(acc_bb_cov[file][func])
    print(f"Total # of BBs : {total_bbs}")

    print(
        f"Total # of unique covered funcs: {accumulated_func_cov}/{total_funcs} ({accumulated_func_cov / total_funcs * 100:.1f}%)"
    )
    print(
        f"Total # of unique covered BBs: {accumulated_bb_cov}/{total_bbs} ({accumulated_bb_cov / total_bbs * 100:.1f}%)"
    )

    print(f"# of BBs always covered: {num_bbs_always_covered}")
    print(f"# of BBs 99% covered: {num_bbs_99_covered}")

    if output_fn is not None:

        result = dict()
        result["num_cov_files"] = num_inputs
        result["avg_func_cov"] = avg_func_cov
        result["avg_bb_cov"] = avg_bb_cov
        result["num_zero_cov_files"] = num_zero_cov
        result["total_source_files"] = len(acc_bb_cov)
        result["total_funcs"] = total_funcs
        result["total_bbs"] = total_bbs
        result["accumulated_func_cov"] = accumulated_func_cov
        result["accumulated_bb_cov"] = accumulated_bb_cov
        result["num_bbs_always_covered"] = num_bbs_always_covered
        result["num_bbs_99_covered"] = num_bbs_99_covered
        result["num_funcs_always_covered"] = len(funcs_always_covered)
        result["num_funcs_99_covered"] = len(funcs_99_covered)
        result["funcs_always_covered"] = [
            {"file": file, "func": func} for (file, func) in funcs_always_covered
        ]
        result["funcs_99_covered"] = [
            {"file": file, "func": func} for (file, func) in funcs_99_covered
        ]
        result["acc_bb_cov"] = acc_bb_cov
        result["acc_func_cov"] = acc_func_cov

        with open(output_fn, "w") as outf:
            json.dump(result, outf, indent=2)
        print(f"Wrote coverage data to {output_fn}")


if __name__ == "__main__":
    sys.exit(main(sys.argv))
